- hosts: localhost
  become: true
  tasks: 
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/nvm-setup.yml
    - import_tasks: tasks/docker-setup.yml
